In [114]:
import pandas as pd
import numpy as np

# load spotify data
df = pd.read_csv(r'excel_data\Alltime_Spotify_Streaming_Data.csv')

print(f"Loaded Database: {df.shape[0]} rows, {df.shape[1]} columns")

C:\Users\Stutie Banerjie\AppData\Local\Temp\ipykernel_19232\521454939.py:5: DtypeWarning: Columns (11,12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'excel_data\Alltime_Spotify_Streaming_Data.csv')

Loaded Database: 517209 rows, 22 columns

In [115]:
df

,time_stamp,streaming_platform,ms_played,country_streamed,track_title,track_album_name,track_album_name2,track_spotify_url,episode_name,episode_show_name,...,audiobook_url,audiobook_chapter_url,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2016-01-24T19:10:33Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",6154,US,Tear in My Heart,Twenty One Pilots,Blurryface,spotify:track:3bnVBN67NBEzedqQuWrpP4,NaN,NaN,...,NaN,NaN,NaN,clickrow,endplay,False,True,False,NaN,False
1,2016-01-24T22:08:36Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",240754,US,Fun (feat. Tove Lo),Coldplay,A Head Full of Dreams,spotify:track:7fJFDK6XjYsXcMKNHESbot,NaN,NaN,...,NaN,NaN,NaN,appload,trackdone,False,False,False,NaN,False
2,2016-01-24T22:09:56Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",73585,US,Someone Like You,Adele,21,spotify:track:4kflIGfjdZJW4ot2ioixTB,NaN,NaN,...,NaN,NaN,NaN,trackdone,endplay,False,True,False,NaN,False
3,2016-01-24T22:13:06Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",189386,US,Immortals,Fall Out Boy,American Beauty/American Psycho,spotify:track:3Te8uLyit6X3ncNW8Fp3K2,NaN,NaN,...,NaN,NaN,NaN,clickrow,trackdone,False,False,False,NaN,False
4,2016-01-24T22:17:10Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",243353,US,Scary Monsters and Nice Sprites,Skrillex,Scary Monsters and Nice Sprites EP,spotify:track:4rwpZEcnalkuhPyGkEdhu0,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517204,2025-11-28T23:48:48Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517205,2025-11-28T23:51:13Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517206,2025-11-28T23:53:39Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517207,2025-11-28T23:56:04Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517208,2025-11-28T23:58:29Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False

In [116]:
############################
# STEP 1: HEADERS CLEANING #
############################

df.columns = df.columns.str.replace('_', ' ')

df = df.rename(columns={
    'track album name': 'track artist',
    'track album name2': 'track album name'
})

print(df.columns)

Index(['time stamp', 'streaming platform', 'ms played', 'country streamed',
       'track title', 'track artist', 'track album name', 'track spotify url',
       'episode name', 'episode show name', 'episode spotify url',
       'audiobook title', 'audiobook url', 'audiobook chapter url',
       'audiobook chapter title', 'reason start', 'reason end', 'shuffle',
       'skipped', 'offline', 'offline timestamp', 'incognito mode'],
      dtype='object')

In [117]:
#############################
# STEP 2: CATEGORICAL TYPOS #
#############################

cleanup_map = {
    'Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G920A)': 'SAMSUNG-SM-G920A',
    'iOS 9.2.1 (iPad2,2)': 'iPad2',
    'Android OS 6.0.1 API 23 (samsung, SAMSUNG-SM-G920A)': 'SAMSUNG-SM-G920A',
    'Android OS 7.0 API 24 (samsung, SAMSUNG-SM-G920A)': 'SAMSUNG-SM-G920A',
    'Android-tablet OS 7.0 API 24 (samsung, SAMSUNG-SM-G920A)': 'SAMSUNG-SM-G920A',
    'Android OS 6.0.1 API 23 (HUAWEI, KIW-L24)': 'KIW-L24',
    'Android OS 8.0.0 API 26 (motorola, moto g(6) play)': 'moto g(6) play',
    'Android OS 9 API 28 (motorola, moto g(6) play)': 'moto g(6) play',
    'Android OS 8.0.0 API 26 (samsung, SM-G950U)': 'SM-G950U',
    'Android OS 9 API 28 (samsung, SM-G950U)': 'SM-G950U',
    'Android OS 11 API 30 (samsung, SM-G781U)': 'SM-G781U',
    'Android OS 12 API 31 (samsung, SM-G781U)': 'SM-G781U',
    'not_applicable': np.nan # handle ghost values     
}

df['streaming platform'] = df['streaming platform'].replace(cleanup_map)

print(df['streaming platform'].unique())

['SAMSUNG-SM-G920A' 'iPad2' 'Windows 10 (10.0.14393; x64)'
 'Windows 10 (10.0.15063; x64)' 'Windows 10 (10.0.16299; x64)' 'KIW-L24'
 'moto g(6) play' 'Windows 10 (10.0.17134; x64; AppX)'
 'Partner google cast_tv;BRAVIA_4K_GB;;2.0.0-671-be56159--1.36.151708'
 'Windows 10 (10.0.17763; x64; AppX)'
 'Partner google cast_tv;BRAVIA_4K_GB;;2.0.0-671-be56159--1.36.154871'
 'Partner google cast_tv;BRAVIA_4K_GB;;2.2.1-7d79c17--1.36.154871'
 'SM-G950U' 'Partner google cast_tv;BRAVIA_4K_GB;;3.1.1--1.42.179832'
 'Partner android_tv Sony;BRAVIA4KGB;756a522d9f1648b89e76e80be654456a;;tpapi'
 'Partner google cast_tv;BRAVIA_4K_GB;;3.2.4--1.47.207274'
 'Partner google cast_tv;BRAVIA_4K_GB;;3.3.0--1.47.211678'
 'web_player windows 10;microsoft edge 85.0.564.68;desktop'
 'web_player windows 10;chrome 91.0.4472.77;desktop'
 'Partner roku_tv roku;4200x;4916bf2fd1c54ff2bace038314d21f39;;tpapi'
 'SM-G781U' 'web_player osx 10.15.7;safari 15.2;desktop'
 'Windows 10 (10.0.19044; x64; AppX)' 'android' 'windows' 'osx' 'xbox' nan
 'cast']

In [118]:
###############################
# STEP 3: DATE TIME DATA TYPE #
###############################

print(df['time stamp'].dtype)

df['time stamp'] = pd.to_datetime(df['time stamp'],errors = 'coerce')

df['time stamp']

object

0        2016-01-24 19:10:33+00:00
1        2016-01-24 22:08:36+00:00
2        2016-01-24 22:09:56+00:00
3        2016-01-24 22:13:06+00:00
4        2016-01-24 22:17:10+00:00
                    ...
517204   2025-11-28 23:48:48+00:00
517205   2025-11-28 23:51:13+00:00
517206   2025-11-28 23:53:39+00:00
517207   2025-11-28 23:56:04+00:00
517208   2025-11-28 23:58:29+00:00
Name: time stamp, Length: 517209, dtype: datetime64[ns, UTC]

In [119]:
###################################
# STEP 4: LOGICAL INTEGRITY CHECK #
#      A: (No Start or End)       #
###################################

impossible_track1 = df['reason start'].isna()
impossible_track2 = df['reason end'].isna()

print(df.loc[impossible_track1])
print(df.loc[impossible_track2])

Empty DataFrame
Columns: [time stamp, streaming platform, ms played, country streamed, track title, track artist, track album name, track spotify url, episode name, episode show name, episode spotify url, audiobook title, audiobook url, audiobook chapter url, audiobook chapter title, reason start, reason end, shuffle, skipped, offline, offline timestamp, incognito mode]
Index: []

[0 rows x 22 columns]
Empty DataFrame
Columns: [time stamp, streaming platform, ms played, country streamed, track title, track artist, track album name, track spotify url, episode name, episode show name, episode spotify url, audiobook title, audiobook url, audiobook chapter url, audiobook chapter title, reason start, reason end, shuffle, skipped, offline, offline timestamp, incognito mode]
Index: []

[0 rows x 22 columns]

In [120]:
###################################
# STEP 4: LOGICAL INTEGRITY CHECK #
#      b: (less Than 0 ms Played) #
###################################
# step 4b: check logical integrity (less than 0 ms played)
impossible_track3 = df['ms played'] < 0

print(df.loc[impossible_track3])

Empty DataFrame
Columns: [time stamp, streaming platform, ms played, country streamed, track title, track artist, track album name, track spotify url, episode name, episode show name, episode spotify url, audiobook title, audiobook url, audiobook chapter url, audiobook chapter title, reason start, reason end, shuffle, skipped, offline, offline timestamp, incognito mode]
Index: []

[0 rows x 22 columns]

In [ ]:
#######################################
# STEP 5: REMOVE UNNECESSARY ROWS     #
#      A: (Tracks that are not songs) #
#######################################

# check if there are podcast or audiobook tracks
not_songs = df['episode name'].notna() | df['audiobook title'].notna()
print(df.loc[not_songs])

# remove these tracks from dataframe
df = df[~not_songs]

                      time stamp streaming platform  ms played  \
15286  2016-11-23 00:56:55+00:00   SAMSUNG-SM-G920A       2086
15287  2016-11-23 00:56:56+00:00   SAMSUNG-SM-G920A        770
15288  2016-11-23 01:17:27+00:00   SAMSUNG-SM-G920A    1151551
15441  2016-11-23 23:32:52+00:00   SAMSUNG-SM-G920A        638
15442  2016-11-23 23:38:52+00:00   SAMSUNG-SM-G920A     340052
...                          ...                ...        ...
514434 2025-11-17 05:11:40+00:00            windows     159041
514435 2025-11-17 05:12:55+00:00            windows      61513
515869 2025-11-23 16:50:04+00:00            android       3885
515870 2025-11-23 16:50:12+00:00            android       8205
515871 2025-11-23 18:33:46+00:00            android     411278

       country streamed track title track artist track album name  \
15286                US         NaN          NaN              NaN
15287                US         NaN          NaN              NaN
15288                US         NaN          NaN              NaN
15441                US         NaN          NaN              NaN
15442                US         NaN          NaN              NaN
...                 ...         ...          ...              ...
514434               US         NaN          NaN              NaN
514435               US         NaN          NaN              NaN
515869               US         NaN          NaN              NaN
515870               US         NaN          NaN              NaN
515871               US         NaN          NaN              NaN

       track spotify url                                       episode name  \
15286                NaN  87 - Missing Fathers (Live from Now Hear This ...
15287                NaN                      5 - Foon’s Greatest Swordsman
15288                NaN                                         3 - Flower
15441                NaN                    1 - Hello from the Magic Tavern
15442                NaN                                         3 - Flower
...                  ...                                                ...
514434               NaN                                                NaN
514435               NaN                                                NaN
515869               NaN                                                NaN
515870               NaN                                                NaN
515871               NaN                                                NaN

                  episode show name  ...                        audiobook url  \
15286   Hello From The Magic Tavern  ...                                  NaN
15287   Hello From The Magic Tavern  ...                                  NaN
15288   Hello From The Magic Tavern  ...                                  NaN
15441   Hello From The Magic Tavern  ...                                  NaN
15442   Hello From The Magic Tavern  ...                                  NaN
...                             ...  ...                                  ...
514434                          NaN  ...  spotify:show:6Y9YnKURd1xSiYm9JWLqTV
514435                          NaN  ...  spotify:show:6Y9YnKURd1xSiYm9JWLqTV
515869                          NaN  ...  spotify:show:1jXKql38AYBaITQn4tkcyP
515870                          NaN  ...  spotify:show:1jXKql38AYBaITQn4tkcyP
515871                          NaN  ...  spotify:show:1jXKql38AYBaITQn4tkcyP

                         audiobook chapter url audiobook chapter title  \
15286                                      NaN                     NaN
15287                                      NaN                     NaN
15288                                      NaN                     NaN
15441                                      NaN                     NaN
15442                                      NaN                     NaN
...                                        ...                     ...
514434  spotify:episode:4BQ0iP5XvqwiyBSCqKsbbJ            Introduction
514435  spotify:episode:68WaBmPfyVq8XPIYyAMZ3m               Chapter 1
515869  spotify:episode:6zweNWZDpnUZkhpK72I1Gt               Chapter 1
515870  spotify:episode:4i6T4tT3xedany4W0dJHuY         Opening Credits
515871  spotify:episode:6zweNWZDpnUZkhpK72I1Gt               Chapter 1

       reason start reason end shuffle skipped  offline  offline timestamp  \
15286      clickrow    endplay   False   False    False                NaN
15287      clickrow    endplay   False   False    False                NaN
15288      clickrow    endplay   False   False    False                NaN
15441      clickrow    endplay   False   False    False                NaN
15442      clickrow  trackdone   False   False    False                NaN
...             ...        ...     ...     ...      ...                ...
514434     clickrow  trackdone   False   False    False       1.763356e+09
514435    trackdone    endplay   False    True    False       1.763356e+09
515869      playbtn    endplay   False    True    False       1.763917e+09
515870    trackdone  trackdone   False   False    False       1.763917e+09
515871    trackdone     logout   False   False    False       1.763917e+09

        incognito mode
15286            False
15287            False
15288            False
15441            False
15442            False
...                ...
514434           False
514435           False
515869           False
515870           False
515871           False

[904 rows x 22 columns]

,time stamp,streaming platform,ms played,country streamed,track title,track artist,track album name,track spotify url,episode name,episode show name,...,audiobook url,audiobook chapter url,audiobook chapter title,reason start,reason end,shuffle,skipped,offline,offline timestamp,incognito mode
0,2016-01-24 19:10:33+00:00,SAMSUNG-SM-G920A,6154,US,Tear in My Heart,Twenty One Pilots,Blurryface,spotify:track:3bnVBN67NBEzedqQuWrpP4,NaN,NaN,...,NaN,NaN,NaN,clickrow,endplay,False,True,False,NaN,False
1,2016-01-24 22:08:36+00:00,SAMSUNG-SM-G920A,240754,US,Fun (feat. Tove Lo),Coldplay,A Head Full of Dreams,spotify:track:7fJFDK6XjYsXcMKNHESbot,NaN,NaN,...,NaN,NaN,NaN,appload,trackdone,False,False,False,NaN,False
2,2016-01-24 22:09:56+00:00,SAMSUNG-SM-G920A,73585,US,Someone Like You,Adele,21,spotify:track:4kflIGfjdZJW4ot2ioixTB,NaN,NaN,...,NaN,NaN,NaN,trackdone,endplay,False,True,False,NaN,False
3,2016-01-24 22:13:06+00:00,SAMSUNG-SM-G920A,189386,US,Immortals,Fall Out Boy,American Beauty/American Psycho,spotify:track:3Te8uLyit6X3ncNW8Fp3K2,NaN,NaN,...,NaN,NaN,NaN,clickrow,trackdone,False,False,False,NaN,False
4,2016-01-24 22:17:10+00:00,SAMSUNG-SM-G920A,243353,US,Scary Monsters and Nice Sprites,Skrillex,Scary Monsters and Nice Sprites EP,spotify:track:4rwpZEcnalkuhPyGkEdhu0,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517204,2025-11-28 23:48:48+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517205,2025-11-28 23:51:13+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517206,2025-11-28 23:53:39+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517207,2025-11-28 23:56:04+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517208,2025-11-28 23:58:29+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False

In [ ]:
#######################################
# STEP 5: REMOVE UNNECESSARY ROWS     #
#      B: (Tracks played for 0 ms)    #
#######################################

# check if there are tracks played for 0 seconds
zero_ms = df['ms played'] == 0
print(df.loc[zero_ms])

# remove these tracks from dataframe
df = df[~zero_ms]

                      time stamp streaming platform  ms played  \
101    2016-01-27 20:01:24+00:00   SAMSUNG-SM-G920A          0
102    2016-01-27 20:01:24+00:00   SAMSUNG-SM-G920A          0
127    2016-01-27 22:07:24+00:00   SAMSUNG-SM-G920A          0
133    2016-01-28 03:46:21+00:00   SAMSUNG-SM-G920A          0
172    2016-01-28 03:57:56+00:00   SAMSUNG-SM-G920A          0
...                          ...                ...        ...
514178 2025-11-16 15:19:27+00:00            android          0
514250 2025-11-16 18:22:19+00:00            windows          0
514291 2025-11-16 19:17:59+00:00            windows          0
515880 2025-11-23 22:27:38+00:00            android          0
517104 2025-11-28 18:59:57+00:00            android          0

       country streamed            track title         track artist  \
101                  US  Emperor's New Clothes  Panic! At The Disco
102                  US           You Found Me             The Fray
127                  US         Wait and Bleed             Slipknot
133                  US                Duality             Slipknot
172                  US              Surfacing             Slipknot
...                 ...                    ...                  ...
514178               US        Falling in Love              No Mana
514250               US            Superheroes         YOU LOVE HER
514291               US                  Smoke              Ghastly
515880               US                 CLOSER            JEON SOMI
517104               US           you haunt me                Marzi

                     track album name                     track spotify url  \
101               Death of a Bachelor  spotify:track:3px2rAPu74ltbkf9eZsZ8h
102                          The Fray  spotify:track:4IoYz8XqqdowINzfRrFnhi
127                          Slipknot  spotify:track:2gscB6kDOmrv1P6qs2KXE3
133     Vol. 3: The Subliminal Verses  spotify:track:61mWefnWQOLf90gepjOCb3
172                          Slipknot  spotify:track:0iget4icTqUya9wtpvCTF2
...                               ...                                   ...
514178      I Contain Flashing Images  spotify:track:1LOPw4e9afnq7YqTpuKqpR
514250      Kitsuné: Inner City Angst  spotify:track:3wFX6B2lxM7yoobVU4U890
514291                   Haunted Haus  spotify:track:2USfvfEEmJwxKzMilhqh5n
515880             Chaotic & Confused  spotify:track:5XsrVitCrmP41A6pq827Yq
517104                   you haunt me  spotify:track:6uu9VaSDuWBXsJx8VTmsOJ

       episode name episode show name  ... audiobook url  \
101             NaN               NaN  ...           NaN
102             NaN               NaN  ...           NaN
127             NaN               NaN  ...           NaN
133             NaN               NaN  ...           NaN
172             NaN               NaN  ...           NaN
...             ...               ...  ...           ...
514178          NaN               NaN  ...           NaN
514250          NaN               NaN  ...           NaN
514291          NaN               NaN  ...           NaN
515880          NaN               NaN  ...           NaN
517104          NaN               NaN  ...           NaN

       audiobook chapter url audiobook chapter title reason start reason end  \
101                      NaN                     NaN       fwdbtn     fwdbtn
102                      NaN                     NaN       fwdbtn     fwdbtn
127                      NaN                     NaN       fwdbtn    backbtn
133                      NaN                     NaN       fwdbtn     fwdbtn
172                      NaN                     NaN       fwdbtn     fwdbtn
...                      ...                     ...          ...        ...
514178                   NaN                     NaN    trackdone     logout
514250                   NaN                     NaN       remote  trackdone
514291                   NaN                     NaN    trackdone     fwdbtn
515880                   NaN                     NaN       fwdbtn     fwdbtn
517104                   NaN                     NaN    trackdone    backbtn

       shuffle skipped  offline  offline timestamp  incognito mode
101      False    True    False                NaN           False
102      False    True    False                NaN           False
127       True    True    False                NaN           False
133       True    True    False                NaN           False
172       True    True    False                NaN           False
...        ...     ...      ...                ...             ...
514178    True   False    False       1.763306e+09           False
514250   False   False    False       1.763317e+09           False
514291   False    True    False       1.763321e+09           False
515880    True    True    False       1.763937e+09           False
517104    True    True    False       1.764356e+09           False

[6394 rows x 22 columns]

,time stamp,streaming platform,ms played,country streamed,track title,track artist,track album name,track spotify url,episode name,episode show name,...,audiobook url,audiobook chapter url,audiobook chapter title,reason start,reason end,shuffle,skipped,offline,offline timestamp,incognito mode
0,2016-01-24 19:10:33+00:00,SAMSUNG-SM-G920A,6154,US,Tear in My Heart,Twenty One Pilots,Blurryface,spotify:track:3bnVBN67NBEzedqQuWrpP4,NaN,NaN,...,NaN,NaN,NaN,clickrow,endplay,False,True,False,NaN,False
1,2016-01-24 22:08:36+00:00,SAMSUNG-SM-G920A,240754,US,Fun (feat. Tove Lo),Coldplay,A Head Full of Dreams,spotify:track:7fJFDK6XjYsXcMKNHESbot,NaN,NaN,...,NaN,NaN,NaN,appload,trackdone,False,False,False,NaN,False
2,2016-01-24 22:09:56+00:00,SAMSUNG-SM-G920A,73585,US,Someone Like You,Adele,21,spotify:track:4kflIGfjdZJW4ot2ioixTB,NaN,NaN,...,NaN,NaN,NaN,trackdone,endplay,False,True,False,NaN,False
3,2016-01-24 22:13:06+00:00,SAMSUNG-SM-G920A,189386,US,Immortals,Fall Out Boy,American Beauty/American Psycho,spotify:track:3Te8uLyit6X3ncNW8Fp3K2,NaN,NaN,...,NaN,NaN,NaN,clickrow,trackdone,False,False,False,NaN,False
4,2016-01-24 22:17:10+00:00,SAMSUNG-SM-G920A,243353,US,Scary Monsters and Nice Sprites,Skrillex,Scary Monsters and Nice Sprites EP,spotify:track:4rwpZEcnalkuhPyGkEdhu0,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517204,2025-11-28 23:48:48+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517205,2025-11-28 23:51:13+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517206,2025-11-28 23:53:39+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517207,2025-11-28 23:56:04+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517208,2025-11-28 23:58:29+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False

In [128]:
######################################
# STEP 6: REMOVE UNNECESSARY COLUMNS #
######################################

df = df.drop(['episode name', 'episode show name', 'episode spotify url', 
              'audiobook title', 'audiobook url', 'audiobook chapter url',
              'audiobook chapter title', 'offline timestamp'],axis=1)

df

,time stamp,streaming platform,ms played,country streamed,track title,track artist,track album name,track spotify url,reason start,reason end,shuffle,skipped,offline,incognito mode
0,2016-01-24 19:10:33+00:00,SAMSUNG-SM-G920A,6154,US,Tear in My Heart,Twenty One Pilots,Blurryface,spotify:track:3bnVBN67NBEzedqQuWrpP4,clickrow,endplay,False,True,False,False
1,2016-01-24 22:08:36+00:00,SAMSUNG-SM-G920A,240754,US,Fun (feat. Tove Lo),Coldplay,A Head Full of Dreams,spotify:track:7fJFDK6XjYsXcMKNHESbot,appload,trackdone,False,False,False,False
2,2016-01-24 22:09:56+00:00,SAMSUNG-SM-G920A,73585,US,Someone Like You,Adele,21,spotify:track:4kflIGfjdZJW4ot2ioixTB,trackdone,endplay,False,True,False,False
3,2016-01-24 22:13:06+00:00,SAMSUNG-SM-G920A,189386,US,Immortals,Fall Out Boy,American Beauty/American Psycho,spotify:track:3Te8uLyit6X3ncNW8Fp3K2,clickrow,trackdone,False,False,False,False
4,2016-01-24 22:17:10+00:00,SAMSUNG-SM-G920A,243353,US,Scary Monsters and Nice Sprites,Skrillex,Scary Monsters and Nice Sprites EP,spotify:track:4rwpZEcnalkuhPyGkEdhu0,trackdone,trackdone,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517204,2025-11-28 23:48:48+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,trackdone,trackdone,True,False,False,False
517205,2025-11-28 23:51:13+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,trackdone,trackdone,True,False,False,False
517206,2025-11-28 23:53:39+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,trackdone,trackdone,True,False,False,False
517207,2025-11-28 23:56:04+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,trackdone,trackdone,True,False,False,False
517208,2025-11-28 23:58:29+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,trackdone,trackdone,True,False,False,False