In [65]:
import pandas as pd
import numpy as np

# load spotify data
df = pd.read_csv(r'excel_data\Alltime_Spotify_Streaming_Data.csv')

print(f"Loaded Database: {df.shape[0]} rows, {df.shape[1]} columns")

C:\Users\Stutie Banerjie\AppData\Local\Temp\ipykernel_19232\521454939.py:5: DtypeWarning: Columns (11,12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'excel_data\Alltime_Spotify_Streaming_Data.csv')

Loaded Database: 517209 rows, 22 columns

In [66]:
df

,time_stamp,streaming_platform,ms_played,country_streamed,track_title,track_album_name,track_album_name2,track_spotify_url,episode_name,episode_show_name,...,audiobook_url,audiobook_chapter_url,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2016-01-24T19:10:33Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",6154,US,Tear in My Heart,Twenty One Pilots,Blurryface,spotify:track:3bnVBN67NBEzedqQuWrpP4,NaN,NaN,...,NaN,NaN,NaN,clickrow,endplay,False,True,False,NaN,False
1,2016-01-24T22:08:36Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",240754,US,Fun (feat. Tove Lo),Coldplay,A Head Full of Dreams,spotify:track:7fJFDK6XjYsXcMKNHESbot,NaN,NaN,...,NaN,NaN,NaN,appload,trackdone,False,False,False,NaN,False
2,2016-01-24T22:09:56Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",73585,US,Someone Like You,Adele,21,spotify:track:4kflIGfjdZJW4ot2ioixTB,NaN,NaN,...,NaN,NaN,NaN,trackdone,endplay,False,True,False,NaN,False
3,2016-01-24T22:13:06Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",189386,US,Immortals,Fall Out Boy,American Beauty/American Psycho,spotify:track:3Te8uLyit6X3ncNW8Fp3K2,NaN,NaN,...,NaN,NaN,NaN,clickrow,trackdone,False,False,False,NaN,False
4,2016-01-24T22:17:10Z,"Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G...",243353,US,Scary Monsters and Nice Sprites,Skrillex,Scary Monsters and Nice Sprites EP,spotify:track:4rwpZEcnalkuhPyGkEdhu0,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517204,2025-11-28T23:48:48Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517205,2025-11-28T23:51:13Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517206,2025-11-28T23:53:39Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517207,2025-11-28T23:56:04Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517208,2025-11-28T23:58:29Z,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False

In [ ]:
############################
# STEP 1: HEADERS CLEANING #
############################

df.columns = df.columns.str.replace('_', ' ')

df = df.rename(columns={
    'track album name': 'track artist',
    'track album name2': 'track album name'
})

print(df.columns)

Index(['time stamp', 'streaming platform', 'ms played', 'country streamed',
       'track title', 'track artist', 'track album name', 'track spotify url',
       'episode name', 'episode show name', 'episode spotify url',
       'audiobook title', 'audiobook url', 'audiobook chapter url',
       'audiobook chapter title', 'reason start', 'reason end', 'shuffle',
       'skipped', 'offline', 'offline timestamp', 'incognito mode'],
      dtype='object')

In [ ]:
#############################
# STEP 2: CATEGORICAL TYPOS #
#############################

print(df['streaming platform'].unique())

cleanup_map = {
    'Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G920A)': 'SAMSUNG-SM-G920A',
    'iOS 9.2.1 (iPad2,2)': 'iPad2',
    'Android OS 6.0.1 API 23 (samsung, SAMSUNG-SM-G920A)': 'SAMSUNG-SM-G920A',
    'Android OS 7.0 API 24 (samsung, SAMSUNG-SM-G920A)': 'SAMSUNG-SM-G920A',
    'Android-tablet OS 7.0 API 24 (samsung, SAMSUNG-SM-G920A)': 'SAMSUNG-SM-G920A',
    'Android OS 6.0.1 API 23 (HUAWEI, KIW-L24)': 'KIW-L24',
    'Android OS 8.0.0 API 26 (motorola, moto g(6) play)': 'moto g(6) play',
    'Android OS 9 API 28 (motorola, moto g(6) play)': 'moto g(6) play',
    'Android OS 8.0.0 API 26 (samsung, SM-G950U)': 'SM-G950U',
    'Android OS 9 API 28 (samsung, SM-G950U)': 'SM-G950U',
    'Android OS 11 API 30 (samsung, SM-G781U)': 'SM-G781U',
    'Android OS 12 API 31 (samsung, SM-G781U)': 'SM-G781U',
    'not_applicable': np.nan # handle ghost values     
}

df['streaming platform'] = df['streaming platform'].replace(cleanup_map)

print(df['streaming platform'].unique())

['Android OS 5.1.1 API 22 (samsung, SAMSUNG-SM-G920A)'
 'iOS 9.2.1 (iPad2,2)'
 'Android OS 6.0.1 API 23 (samsung, SAMSUNG-SM-G920A)'
 'Windows 10 (10.0.14393; x64)'
 'Android OS 7.0 API 24 (samsung, SAMSUNG-SM-G920A)'
 'Windows 10 (10.0.15063; x64)' 'Windows 10 (10.0.16299; x64)'
 'Android-tablet OS 7.0 API 24 (samsung, SAMSUNG-SM-G920A)'
 'Android OS 6.0.1 API 23 (HUAWEI, KIW-L24)'
 'Android OS 8.0.0 API 26 (motorola, moto g(6) play)'
 'Windows 10 (10.0.17134; x64; AppX)'
 'Partner google cast_tv;BRAVIA_4K_GB;;2.0.0-671-be56159--1.36.151708'
 'Windows 10 (10.0.17763; x64; AppX)'
 'Android OS 9 API 28 (motorola, moto g(6) play)'
 'Partner google cast_tv;BRAVIA_4K_GB;;2.0.0-671-be56159--1.36.154871'
 'Partner google cast_tv;BRAVIA_4K_GB;;2.2.1-7d79c17--1.36.154871'
 'Android OS 8.0.0 API 26 (samsung, SM-G950U)'
 'Android OS 9 API 28 (samsung, SM-G950U)'
 'Partner google cast_tv;BRAVIA_4K_GB;;3.1.1--1.42.179832'
 'Partner android_tv Sony;BRAVIA4KGB;756a522d9f1648b89e76e80be654456a;;tpapi'
 'Partner google cast_tv;BRAVIA_4K_GB;;3.2.4--1.47.207274'
 'Partner google cast_tv;BRAVIA_4K_GB;;3.3.0--1.47.211678'
 'web_player windows 10;microsoft edge 85.0.564.68;desktop'
 'web_player windows 10;chrome 91.0.4472.77;desktop'
 'Partner roku_tv roku;4200x;4916bf2fd1c54ff2bace038314d21f39;;tpapi'
 'Android OS 11 API 30 (samsung, SM-G781U)'
 'web_player osx 10.15.7;safari 15.2;desktop'
 'Android OS 12 API 31 (samsung, SM-G781U)'
 'Windows 10 (10.0.19044; x64; AppX)' 'android' 'windows' 'osx' 'xbox'
 'not_applicable' 'cast']
['SAMSUNG-SM-G920A' 'iPad2' 'Windows 10 (10.0.14393; x64)'
 'Windows 10 (10.0.15063; x64)' 'Windows 10 (10.0.16299; x64)' 'KIW-L24'
 'moto g(6) play' 'Windows 10 (10.0.17134; x64; AppX)'
 'Partner google cast_tv;BRAVIA_4K_GB;;2.0.0-671-be56159--1.36.151708'
 'Windows 10 (10.0.17763; x64; AppX)'
 'Partner google cast_tv;BRAVIA_4K_GB;;2.0.0-671-be56159--1.36.154871'
 'Partner google cast_tv;BRAVIA_4K_GB;;2.2.1-7d79c17--1.36.154871'
 'SM-G950U' 'Partner google cast_tv;BRAVIA_4K_GB;;3.1.1--1.42.179832'
 'Partner android_tv Sony;BRAVIA4KGB;756a522d9f1648b89e76e80be654456a;;tpapi'
 'Partner google cast_tv;BRAVIA_4K_GB;;3.2.4--1.47.207274'
 'Partner google cast_tv;BRAVIA_4K_GB;;3.3.0--1.47.211678'
 'web_player windows 10;microsoft edge 85.0.564.68;desktop'
 'web_player windows 10;chrome 91.0.4472.77;desktop'
 'Partner roku_tv roku;4200x;4916bf2fd1c54ff2bace038314d21f39;;tpapi'
 'SM-G781U' 'web_player osx 10.15.7;safari 15.2;desktop'
 'Windows 10 (10.0.19044; x64; AppX)' 'android' 'windows' 'osx' 'xbox' nan
 'cast']

In [ ]:
# step 3: date parsing
print(df['time stamp'].dtype)

df['time stamp'] = pd.to_datetime(df['time stamp'],errors = 'coerce')

df

object

,time stamp,streaming platform,ms played,country streamed,track title,track artist,track album name,track spotify url,episode name,episode show name,...,audiobook url,audiobook chapter url,audiobook chapter title,reason start,reason end,shuffle,skipped,offline,offline timestamp,incognito mode
0,2016-01-24 19:10:33+00:00,SAMSUNG-SM-G920A,6154,US,Tear in My Heart,Twenty One Pilots,Blurryface,spotify:track:3bnVBN67NBEzedqQuWrpP4,NaN,NaN,...,NaN,NaN,NaN,clickrow,endplay,False,True,False,NaN,False
1,2016-01-24 22:08:36+00:00,SAMSUNG-SM-G920A,240754,US,Fun (feat. Tove Lo),Coldplay,A Head Full of Dreams,spotify:track:7fJFDK6XjYsXcMKNHESbot,NaN,NaN,...,NaN,NaN,NaN,appload,trackdone,False,False,False,NaN,False
2,2016-01-24 22:09:56+00:00,SAMSUNG-SM-G920A,73585,US,Someone Like You,Adele,21,spotify:track:4kflIGfjdZJW4ot2ioixTB,NaN,NaN,...,NaN,NaN,NaN,trackdone,endplay,False,True,False,NaN,False
3,2016-01-24 22:13:06+00:00,SAMSUNG-SM-G920A,189386,US,Immortals,Fall Out Boy,American Beauty/American Psycho,spotify:track:3Te8uLyit6X3ncNW8Fp3K2,NaN,NaN,...,NaN,NaN,NaN,clickrow,trackdone,False,False,False,NaN,False
4,2016-01-24 22:17:10+00:00,SAMSUNG-SM-G920A,243353,US,Scary Monsters and Nice Sprites,Skrillex,Scary Monsters and Nice Sprites EP,spotify:track:4rwpZEcnalkuhPyGkEdhu0,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517204,2025-11-28 23:48:48+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517205,2025-11-28 23:51:13+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517206,2025-11-28 23:53:39+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517207,2025-11-28 23:56:04+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False
517208,2025-11-28 23:58:29+00:00,windows,144522,US,Fever,Buckshot,Fever,spotify:track:09xhawlPUifhftf8zuie7w,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.764374e+09,False

In [ ]:
# step 4a: check logical integrity (no start or end)
impossible_track1 = df['reason start'].isna()
impossible_track2 = df['reason end'].isna()

print(df.loc[impossible_track1])
print(df.loc[impossible_track2])

Empty DataFrame
Columns: [time stamp, streaming platform, ms played, country streamed, track title, track artist, track album name, track spotify url, episode name, episode show name, episode spotify url, audiobook title, audiobook url, audiobook chapter url, audiobook chapter title, reason start, reason end, shuffle, skipped, offline, offline timestamp, incognito mode]
Index: []

[0 rows x 22 columns]
Empty DataFrame
Columns: [time stamp, streaming platform, ms played, country streamed, track title, track artist, track album name, track spotify url, episode name, episode show name, episode spotify url, audiobook title, audiobook url, audiobook chapter url, audiobook chapter title, reason start, reason end, shuffle, skipped, offline, offline timestamp, incognito mode]
Index: []

[0 rows x 22 columns]

In [73]:
# step 4b: check logical integrity (less than 0 ms played)
impossible_track3 = df['ms played'] < 0

print(df.loc[impossible_track3])

Empty DataFrame
Columns: [time stamp, streaming platform, ms played, country streamed, track title, track artist, track album name, track spotify url, episode name, episode show name, episode spotify url, audiobook title, audiobook url, audiobook chapter url, audiobook chapter title, reason start, reason end, shuffle, skipped, offline, offline timestamp, incognito mode]
Index: []

[0 rows x 22 columns]